FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY core/go.mod core/go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY core/* ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "$(LDFLAGS)" -o orca .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/orca .

ENV GRPC_PORT=50051 \
    ENVIRONMENT=production

# Expose gRPC port
EXPOSE 50051

# Set the entrypoint
ENTRYPOINT ["./server"]

