// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WindowService_RegisterWindow_FullMethodName = "/WindowService/RegisterWindow"
)

// WindowServiceClient is the client API for WindowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WindowServiceClient interface {
	RegisterWindow(ctx context.Context, in *Window, opts ...grpc.CallOption) (*Status, error)
}

type windowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWindowServiceClient(cc grpc.ClientConnInterface) WindowServiceClient {
	return &windowServiceClient{cc}
}

func (c *windowServiceClient) RegisterWindow(ctx context.Context, in *Window, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, WindowService_RegisterWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindowServiceServer is the server API for WindowService service.
// All implementations must embed UnimplementedWindowServiceServer
// for forward compatibility.
type WindowServiceServer interface {
	RegisterWindow(context.Context, *Window) (*Status, error)
	mustEmbedUnimplementedWindowServiceServer()
}

// UnimplementedWindowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWindowServiceServer struct{}

func (UnimplementedWindowServiceServer) RegisterWindow(context.Context, *Window) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWindow not implemented")
}
func (UnimplementedWindowServiceServer) mustEmbedUnimplementedWindowServiceServer() {}
func (UnimplementedWindowServiceServer) testEmbeddedByValue()                       {}

// UnsafeWindowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WindowServiceServer will
// result in compilation errors.
type UnsafeWindowServiceServer interface {
	mustEmbedUnimplementedWindowServiceServer()
}

func RegisterWindowServiceServer(s grpc.ServiceRegistrar, srv WindowServiceServer) {
	// If the following call pancis, it indicates UnimplementedWindowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WindowService_ServiceDesc, srv)
}

func _WindowService_RegisterWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Window)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowServiceServer).RegisterWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WindowService_RegisterWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowServiceServer).RegisterWindow(ctx, req.(*Window))
	}
	return interceptor(ctx, in, info, handler)
}

// WindowService_ServiceDesc is the grpc.ServiceDesc for WindowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WindowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WindowService",
	HandlerType: (*WindowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWindow",
			Handler:    _WindowService_RegisterWindow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
