// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlgorithmType struct {
	Name       string
	Version    string
	WindowType string
	DependsOn  pgtype.Text
	CreatedAt  pgtype.Timestamp
}

type Window struct {
	ID         int32
	TimeFrom   int64
	TimeTo     int64
	WindowType string
	CreatedAt  pgtype.Timestamp
}

type WindowType struct {
	Name      string
	CreatedAt pgtype.Timestamp
}
