// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlgorithmDependency struct {
	AlgorithmName    string
	AlgorithmVersion string
	DependsOnName    string
	DependsOnVersion string
}

type AlgorithmType struct {
	Name           string
	Version        string
	WindowTypeName string
	CreatedAt      pgtype.Timestamp
}

type Window struct {
	ID             int32
	TimeFrom       int64
	TimeTo         int64
	WindowTypeName string
	CreatedAt      pgtype.Timestamp
}

type WindowType struct {
	Name      string
	CreatedAt pgtype.Timestamp
}
