# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrcaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWindow = channel.unary_unary(
                '/OrcaService/RegisterWindow',
                request_serializer=service__pb2.Window.SerializeToString,
                response_deserializer=service__pb2.Status.FromString,
                _registered_method=True)
        self.RegisterWindowType = channel.unary_unary(
                '/OrcaService/RegisterWindowType',
                request_serializer=service__pb2.WindowType.SerializeToString,
                response_deserializer=service__pb2.Status.FromString,
                _registered_method=True)
        self.RegisterAlgorithmType = channel.unary_unary(
                '/OrcaService/RegisterAlgorithmType',
                request_serializer=service__pb2.AlgorithmType.SerializeToString,
                response_deserializer=service__pb2.Status.FromString,
                _registered_method=True)
        self.RegisterResult = channel.unary_unary(
                '/OrcaService/RegisterResult',
                request_serializer=service__pb2.Result.SerializeToString,
                response_deserializer=service__pb2.Status.FromString,
                _registered_method=True)


class OrcaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWindowType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAlgorithmType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrcaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWindow,
                    request_deserializer=service__pb2.Window.FromString,
                    response_serializer=service__pb2.Status.SerializeToString,
            ),
            'RegisterWindowType': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWindowType,
                    request_deserializer=service__pb2.WindowType.FromString,
                    response_serializer=service__pb2.Status.SerializeToString,
            ),
            'RegisterAlgorithmType': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAlgorithmType,
                    request_deserializer=service__pb2.AlgorithmType.FromString,
                    response_serializer=service__pb2.Status.SerializeToString,
            ),
            'RegisterResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterResult,
                    request_deserializer=service__pb2.Result.FromString,
                    response_serializer=service__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrcaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OrcaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrcaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrcaService/RegisterWindow',
            service__pb2.Window.SerializeToString,
            service__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWindowType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrcaService/RegisterWindowType',
            service__pb2.WindowType.SerializeToString,
            service__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAlgorithmType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrcaService/RegisterAlgorithmType',
            service__pb2.AlgorithmType.SerializeToString,
            service__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrcaService/RegisterResult',
            service__pb2.Result.SerializeToString,
            service__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
