// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Algorithm struct {
	ID           int64
	Name         string
	Version      string
	ProcessorID  int64
	WindowTypeID int64
	Created      pgtype.Timestamp
}

type AlgorithmDependency struct {
	ID               int64
	FromAlgorithmID  int64
	ToAlgorithmID    int64
	FromWindowTypeID int64
	ToWindowTypeID   int64
	FromProcessorID  int64
	ToProcessorID    int64
	Created          pgtype.Timestamp
}

type AlgorithmExecutionPath struct {
	FinalAlgoID      int64
	NumDependencies  int32
	AlgoIDPath       string
	WindowTypeIDPath string
	ProcIDPath       string
}

type AlgorithmRequiredDatagetter struct {
	ID           int64
	DataGetterID int64
	AlgorithmID  int64
}

type DataGetter struct {
	ID           int64
	ProcessorID  int64
	Name         string
	WindowTypeID int64
	TtlSeconds   int64
	MaxSizeBytes int64
}

type Processor struct {
	ID               int64
	Name             string
	Runtime          string
	ConnectionString string
	Created          pgtype.Timestamp
}

type Result struct {
	ID           int64
	WindowsID    pgtype.Int8
	WindowTypeID pgtype.Int8
	AlgorithmID  pgtype.Int8
	ResultValue  pgtype.Float8
	ResultArray  []float64
	ResultJson   []byte
}

type Window struct {
	ID           int64
	WindowTypeID int64
	TimeFrom     int64
	TimeTo       int64
	Origin       string
	Created      pgtype.Timestamp
}

type WindowType struct {
	ID      int64
	Name    string
	Version string
	Created pgtype.Timestamp
}
